server:
  port: 8080
spring:
  application:
    name: banking_app

  datasource:
    url: jdbc:h2:mem:bank-db
    username: sa
    password: s3cr3t
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

springdoc:
  api-docs:
    path: /api-docs